import React from "react";
import { useFetch } from "../utils/useFetch";
import Head from "next/head";

const Home = ({ data }) => {
  console.log(data);
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Home</div>
    </>
  );
};

export default Home;

export async function getServerSideProps(context) {
  const res = await useFetch("/users");
  const data = await res.json();
  return {
    props: { data }, // will be passed to the page component as props
  };
}
