import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Select from "../components/Select";
import TextInput from "../components/TextInput";
// import TextField from "@mui/material/TextField";
import SelectInput from "../components/Select2";
import AddReactionIcon from "@mui/icons-material/AddReaction";
import Calender from "../components/Calender";
import Date from "../components/Date";

export default function Home() {
  const options = [
    { value: "chocolate", label: "Chocolate", icon: <AddReactionIcon /> },
    { value: "strawberry", label: "Strawberry", icon: <AddReactionIcon /> },
    { value: "vanilla", label: "Vanilla", icon: <AddReactionIcon /> },
  ];

  const selectHanlder = (val) => {
    console.log(val);
  };

  return (
    <>
      <Head>
        <title>Index page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex items-center justify-around p-5 w-100">
        <p className="">hello world</p>
        <div className="flex items-center">
          {/* <Select /> */}
          <SelectInput
            className="w-[200px]"
            options={options}
            onChange={selectHanlder}
          />
          <TextInput />
        </div>
        <div>
          {/* <Calender label="loan start day" /> */}
          <Date />
        </div>
      </main>
    </>
  );
}
