import React, { useEffect, useState } from "react";
import Head from "next/head";
import Users from "../components/users/Users";
import AddUser from "../components/users/AddUser";
import Test from "../components/Test";
import axios from "../utils/axios";

export default function Home({ data }) {
  const [users, setUsers] = useState(null);

  useEffect(() => {
    // const fetchUsers = () => {
    //   axios
    //     .get("http://localhost:3000/api/users")
    //     .then((data) => setUsers(data.data))
    //     .catch((err) => {
    //       console.log("error home");
    //       console.log(err.message);
    //     });
    // };
    // fetchUsers();
    // const fetchUsers = () => {
    //   fetch("http://localhost:3000/api/users")
    //     .then((res) => res.json())
    //     .then((data) => setUsers(data))
    //     .catch((err) => {
    //       console.log("error home");
    //       console.log(err.message);
    //     });
    // };
    // fetchUsers();
  }, []);

  // console.log(users);

  if (!data) return <p>somthing went wrong</p>;

  return (
    <>
      <Head>
        <title>Index page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-around p-5 w-100">
        <Users users={data} comp={<Test />} />
        <AddUser users={data} setUsers={setUsers} />
      </main>
    </>
  );
}

export async function getServerSideProps(context) {
  const { data } = await axios.get("/users");
  return {
    props: {
      data,
    }, // will be passed to the page component as props
  };
}
