import React, { useEffect, useState } from "react";
import Head from "next/head";
import Users from "../components/users/Users";
import AddUser from "../components/users/AddUser";
import Test from "../components/Test";
import axios from "../utils/axios";
import Form from "../components/Form";
import axiosPrivate from "../axiosPrivate";
import router from "next/router";
import useAxiosPrivate from "../hooks/useAxiosPrivate";

export default function Home() {
  const [users, setUsers] = useState(null);
  const axiospriv = useAxiosPrivate();

  // useEffect(() => {
  //   const fetchUsers = () => {
  //     axios
  //       .get("http://localhost:3000/api/users")
  //       .then((data) => {
  //         console.log("success");
  //         setUsers(data.data);
  //       })
  //       .catch((err) => {
  //         console.log("error home");
  //         console.log(err.message);
  //       });
  //   };
  //   fetchUsers();
  // }, []);

  // useEffect(() => {
  //   axiosPrivate
  //     .get("/guest/atms")
  //     .then((res) => console.log(res))
  //     .catch((err) => err);
  // }, []);

  // useEffect(() => {
  //   axiosPrivate
  //     .post("/auth/register", {
  //       email: "hossam.salem667@gmail.com",
  //       password: "1994@Barcelona",
  //     })
  //     .then((res) => console.log(res))
  //     .catch((err) => err);
  // }, []);

  // useEffect(() => {
  //   axiospriv
  //     .get("https://jsonplaceholder.typicode.com/todos/1")
  //     .then((res) => console.log(res))
  //     .catch((err) => err);
  // }, []);

  // const tokenStr =
  //   "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE2NzU0NjQ2MjEsImV4cCI6MTY3NTQ2NTYyMX0.gQCYmVGmcnDEtrvFGWYAPc9J1Tste8xRpR9zd_hNgTg";

  // useEffect(() => {
  //   axiosPrivate
  //     .get("http://localhost:3500/refresh", {
  //       headers: { Authorization: `Bearer ${tokenStr}` },
  //     })
  //     .then((res) => console.log(res))
  //     .catch((err) => err);
  // }, []);
  let dataa = {
    name: "hossam",
    age: 28,
  };

  const objectToFormData = (object) => {
    let data = new FormData();
    for (let i in object) {
      // if (object[i] && !Array.isArray(object[i])) {
      if (object[i]) {
        data.append(i, object[i]);
      }

      // if (Array.isArray(object[i])) {
      //   for (let i2 in object[i]) {
      //     data.append(`${i}[]`, object[i][i2]);
      //   }
      // }
    }
    return data;
  };

  console.log(objectToFormData(dataa));

  return (
    <>
      <Head>
        <title>Index page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-around p-5 w-100">
        <nav className="flex items-center justify-center">
          <div>
            <button
              className="px-3 py-2 mx-3 mt-3 text-white bg-black rounded-md"
              onClick={() => router.push("/login")}
            >
              Login
            </button>
          </div>
          <div>
            <button
              className="px-3 py-2 mt-3 text-white bg-black rounded-md"
              onClick={() => router.push("/register")}
            >
              Register
            </button>
          </div>
        </nav>
      </main>
    </>
  );
}

// export async function getServerSideProps(context) {
//   const { data } = await axios.get("/users");
//   return {
//     props: {
//       data,
//     },
//   };
// }
